import { Injectable, NotFoundException, ConflictException } from '@nestjs/common';
import { threadSchema, messageSchema, pageSchema } from 'shared';
import { z } from 'zod';
import { db } from '../../database/prisma';
import { env } from '../../config/env';
const stateSchema = z.enum(['OPEN', 'PENDING_STAFF', 'PENDING_USER', 'CLOSED']);
@Injectable()
export class SupportService {
  async list(userId: string | null, input: unknown) { const q = pageSchema.parse(input); const where = { ...(userId ? { userId } : {}), ...(q.status ? { status: stateSchema.parse(q.status) } : {}), ...(q.q ? { subject: { contains: q.q, mode: 'insensitive' as const } } : {}) }; const [items, total] = await Promise.all([db.supportThread.findMany({ where, orderBy: { updatedAt: 'desc' }, take: q.limit, skip: (q.page - 1) * q.limit, include: { user: { select: { name: true } } } }), db.supportThread.count({ where })]); return { items, total, page: q.page, limit: q.limit, responseHours: env.SUPPORT_RESPONSE_HOURS }; }
  async create(userId: string, input: unknown) { const { body, subject, category } = threadSchema.parse(input); return db.supportThread.create({ data: { userId, subject, category, messages: { create: { senderId: userId, body } } } }); }
  async own(id: string, userId: string | null) { const thread = await db.supportThread.findFirst({ where: { id, ...(userId ? { userId } : {}) } }); if (!thread) throw new NotFoundException(); return thread; }
  async get(id: string, userId: string | null) { const thread = await this.own(id, userId); const [messages, assigned] = await Promise.all([db.supportMessage.findMany({ where: { threadId: id }, orderBy: { createdAt: 'desc' }, take: 100 }), thread.assignedTo ? db.user.findUnique({ where: { id: thread.assignedTo }, select: { name: true } }) : null]); const notes = !userId ? await db.supportInternalNote.findMany({ where: { threadId: id }, take: 50, orderBy: { createdAt: 'desc' } }) : undefined; return { ...thread, messages: messages.reverse(), assignedName: assigned?.name ?? null, responseHours: env.SUPPORT_RESPONSE_HOURS, ...(!userId ? { notes } : {}) }; }
  async message(id: string, actorId: string, staff: boolean, input: unknown) { const { body } = messageSchema.parse(input); const thread = await this.own(id, staff ? null : actorId); if (thread.status === 'CLOSED') throw new ConflictException({ code: 'THREAD_CLOSED', message: 'Reabre la conversación para enviar un mensaje.' }); return db.$transaction(async tx => { const message = await tx.supportMessage.create({ data: { threadId: id, senderId: actorId, staff, body } }); await tx.supportThread.update({ where: { id }, data: { status: staff ? 'PENDING_USER' : 'PENDING_STAFF', ...(staff ? { assignedTo: actorId } : {}) } }); if (staff) await tx.adminAuditLog.create({ data: { actorId, action: 'SUPPORT_REPLY', entityId: id, after: { messageId: message.id } } }); return message; }); }
  async state(id: string, actorId: string, staff: boolean, input: unknown) { const { status } = z.object({ status: stateSchema }).strict().parse(input); if (!staff && !['CLOSED', 'PENDING_STAFF'].includes(status)) throw new ConflictException(); const thread = await this.own(id, staff ? null : actorId); return db.$transaction(async tx => { const result = await tx.supportThread.update({ where: { id }, data: { status } }); if (staff) await tx.adminAuditLog.create({ data: { actorId, action: 'SUPPORT_STATE', entityId: id, before: { status: thread.status }, after: { status } } }); return result; }); }
}
