'use client';
import { useEffect, useRef, useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import type { Evaluation } from 'shared';
import { api, post, patch } from '../../services/api';
import type { ContentDetail } from '../study/theory-detail';
import { PageHeader, Loading, ErrorNotice, DemoNotice, ActionLink } from '../../components/ui/common';
import { EvaluationView, type McqResult } from '../../components/cases/evaluation';
import { McqForm } from '../../components/cases/mcq-form';
interface Attempt { id: string; status: string; answer: string; answers: Record<string, number | null>; evaluation: Evaluation | McqResult | null; score: number | null; snapshot: { title: string; body: string; data: ContentDetail['data'] }; }
export function CaseWorkspace({ slug }: { slug: string }) {
  const client = useQueryClient(); const [attemptId, setAttemptId] = useState('');
  const query = useQuery({ queryKey: ['case', slug], queryFn: () => api<ContentDetail>(`practical-cases/${slug}`) });
  const history = useQuery({ queryKey: ['history', slug], queryFn: () => api<{ id: string; status: string; score: number | null; createdAt: string }[]>(`practical-cases/${slug}/attempts`), enabled: !!query.data });
  const create = useMutation({ mutationFn: () => post<{ id: string }>(`practical-cases/${slug}/attempts`), onSuccess: data => { setAttemptId(data.id); client.invalidateQueries({ queryKey: ['history', slug] }); } });
  const attempt = useQuery({ queryKey: ['attempt', attemptId], queryFn: () => api<Attempt>(`case-attempts/${attemptId}`), enabled: !!attemptId, refetchInterval: q => ['QUEUED', 'PROCESSING'].includes(q.state.data?.status ?? '') ? 2000 : false });
  if (query.isPending) return <Loading />;
  if (!query.data) return <><ErrorNotice error={query.error} /><ActionLink href="/app/suscripcion">Ver mi plan</ActionLink></>;
  const c = query.data;
  return <><Link href="/app/supuestos">← Banco de supuestos</Link><PageHeader eyebrow={`${c.format === 'MCQ' ? 'TIPO TEST' : 'DESARROLLO'} · ${c.minutes} MINUTOS ORIENTATIVOS`} title={c.title} description={c.summary} /><DemoNotice /><section className="panel"><p className="eyebrow">ENUNCIADO</p><p>{attempt.data?.snapshot.body ?? c.body}</p>{c.data.theorySlug && <Link href={`/app/temario/${c.data.theorySlug}`}>Consultar teoría relacionada →</Link>}</section><ErrorNotice error={create.error ?? attempt.error} />{!attemptId && <div className="stack" style={{ marginTop: 22 }}><button className="button" onClick={() => create.mutate()} disabled={create.isPending}>Comenzar o continuar respuesta</button>{history.data && history.data.length > 0 && <section className="panel"><h2>Tus intentos</h2>{history.data.map(a => <div className="list-item" key={a.id}><span>{new Date(a.createdAt).toLocaleDateString('es-ES')} · {a.status}{a.score !== null ? ` · ${a.score}/100` : ''}</span><button className="button secondary small" onClick={() => setAttemptId(a.id)}>Abrir intento</button></div>)}</section>}</div>}{attempt.data && <AttemptEditor key={attempt.data.id} attempt={attempt.data} format={c.format} onUpdate={() => { client.invalidateQueries({ queryKey: ['attempt', attemptId] }); client.invalidateQueries({ queryKey: ['progress'] }); }} />}</>;
}
function AttemptEditor({ attempt, format, onUpdate }: { attempt: Attempt; format: string; onUpdate: () => void }) {
  const [answer, setAnswer] = useState(attempt.answer); const [answers, setAnswers] = useState(attempt.answers); const [saved, setSaved] = useState('Borrador guardado'); const [error, setError] = useState<Error | null>(null); const pending = useRef<Promise<unknown>>(Promise.resolve()); const lastSaved = useRef(attempt.answer);
  useEffect(() => { if (format === 'MCQ' || attempt.status !== 'DRAFT' || answer === lastSaved.current) return; setSaved('Cambios pendientes…'); const timer = setTimeout(() => { pending.current = pending.current.catch(() => undefined).then(() => patch(`case-attempts/${attempt.id}`, { answer })).then(() => { lastSaved.current = answer; setSaved('Borrador guardado'); }).catch(e => { setError(e); setSaved('No se ha guardado'); }); }, 1000); return () => clearTimeout(timer); }, [answer, attempt.id, attempt.status, format]);
  const submit = useMutation({ mutationFn: async () => { await pending.current; if (format !== 'MCQ') await patch(`case-attempts/${attempt.id}`, { answer }); return post(`case-attempts/${attempt.id}/submit`, format === 'MCQ' ? { answers } : {}); }, onSuccess: onUpdate });
  const saveChoices = (value: Record<string, number | null>) => { setAnswers(value); setSaved('Guardando…'); pending.current = pending.current.catch(() => undefined).then(() => patch(`case-attempts/${attempt.id}`, { answers: value })).then(() => { setSaved('Borrador guardado'); }).catch(e => { setError(e); setSaved('No se ha guardado'); }); };
  if (attempt.status === 'COMPLETED' && attempt.evaluation) return <div style={{ marginTop: 22 }}><EvaluationView score={attempt.score ?? 0} evaluation={attempt.evaluation} /></div>;
  if (['QUEUED', 'PROCESSING'].includes(attempt.status)) return <div className="notice" role="status">Tu respuesta está guardada. La evaluación se está procesando; puedes salir y volver a este intento.</div>;
  if (attempt.status === 'FAILED') return <div className="notice error">La evaluación no se ha completado. Tu respuesta sigue guardada. <Link href="/app/soporte">Consulta al equipo</Link>.</div>;
  return <section className="panel" style={{ marginTop: 22 }}><h2>Tu respuesta</h2><ErrorNotice error={error ?? submit.error} />{format === 'MCQ' ? <McqForm questions={attempt.snapshot.data.questions} answers={answers} onChange={saveChoices} disabled={submit.isPending} /> : <><label htmlFor="answer">Explica y justifica tu actuación</label><textarea id="answer" className="answer-editor" value={answer} maxLength={30000} onChange={e => setAnswer(e.target.value)} placeholder="1. Hechos relevantes…" disabled={submit.isPending} /><div className="editor-footer"><span>{answer.trim() ? answer.trim().split(/\s+/).length : 0} palabras</span><span role="status">{saved}</span></div></>}<button className="button" style={{ marginTop: 24 }} disabled={submit.isPending || (format !== 'MCQ' && answer.trim().length < 30)} onClick={() => submit.mutate()}>{submit.isPending ? 'Guardando y entregando…' : 'Entregar respuesta'}</button><p className="fine muted" style={{ marginTop: 12 }}>La entrega bloquea esta respuesta. Podrás consultar su resultado y conservarás el historial.</p></section>;
}
