'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { BookOpen, ArrowUpRight, Clock3 } from 'lucide-react';
import Link from 'next/link';
import { categories, categoryLabels } from 'shared';
import { api } from '../../services/api';
import type { ContentSummary, Page } from '../../types/api';
import { PageHeader, ErrorNotice, Loading, Empty } from '../../components/ui/common';
export const catalog = { temario: { endpoint: 'theory', title: 'Temario práctico', description: 'La teoría que necesitas para construir una buena actuación.' }, supuestos: { endpoint: 'practical-cases', title: 'Banco de supuestos', description: 'Lee, decide y argumenta. Cada caso es una oportunidad de mejorar.' }, examenes: { endpoint: 'exams', title: 'Ponte a prueba', description: 'Simulacros con tiempo y condiciones definidos para cada examen.' }, manual: { endpoint: 'manual', title: 'Manual profesional', description: 'Consulta fichas, fuentes y límites de aplicación.' } };
export function ContentList({ section }: { section: keyof typeof catalog }) {
  const [q, setQ] = useState(''); const [category, setCategory] = useState(''); const [format, setFormat] = useState(''); const [page, setPage] = useState(1); const config = catalog[section];
  const params = new URLSearchParams({ q, page: String(page), limit: '12', ...(category ? { category } : {}), ...(format ? { format } : {}) });
  const query = useQuery({ queryKey: [section, params.toString()], queryFn: () => api<Page<ContentSummary>>(`${config.endpoint}?${params}`) });
  return <><PageHeader eyebrow="APRENDE · APLICA · MEJORA" title={config.title} description={config.description} /><div className="filters"><input aria-label="Buscar contenido" placeholder="Busca por título o concepto…" value={q} onChange={e => { setQ(e.target.value); setPage(1); }} /><select aria-label="Categoría" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">Todas las categorías</option>{categories.map(c => <option key={c} value={c}>{categoryLabels[c]}</option>)}</select>{section === 'supuestos' && <select aria-label="Formato" value={format} onChange={e => setFormat(e.target.value)}><option value="">Todos los formatos</option><option value="DEVELOPMENT">Desarrollo</option><option value="MCQ">Tipo test</option></select>}</div><ErrorNotice error={query.error} />{query.isPending && <Loading />}<div className="list">{query.data?.items.map(c => <article className="list-item" key={c.id}><span className="item-icon"><BookOpen size={21} /></span><div className="item-content"><span className="eyebrow">{categoryLabels[c.category as keyof typeof categoryLabels] ?? c.category}</span><h3><Link href={`/app/${section}/${section === 'examenes' ? c.id : c.slug}`}>{c.title}</Link></h3><p>{c.summary}</p><div className="meta"><span className="actions"><Clock3 size={12} />{c.minutes} min</span><span>{c.format === 'MCQ' ? 'Tipo test' : section === 'supuestos' ? 'Desarrollo' : 'Ficha práctica'}</span>{c.free && <span>Incluido en la prueba gratuita</span>}<span>Contenido demo</span></div></div><Link aria-label={`Abrir ${c.title}`} href={`/app/${section}/${section === 'examenes' ? c.id : c.slug}`}><ArrowUpRight size={22} /></Link></article>)}</div>{query.data?.total === 0 && <Empty title="No hay coincidencias" description="Prueba con otro término o cambia los filtros." />}{query.data && query.data.total > 12 && <div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>Página {page}</span><button className="button secondary" disabled={page * 12 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div>}</>;
}
