import { test, expect } from '@playwright/test';
import { createTestAccount } from '../../backend/test/fixtures';
import { db } from '../../backend/src/database/prisma';
import { rubric, questions } from '../../backend/prisma/seed/content';
import AxeBuilder from '@axe-core/playwright';
test('supuesto, test, examen, permisos, soporte y suspensión con datos reales', async ({ playwright }) => {
  const student = await createTestAccount(); const staff = await createTestAccount('SUPERADMIN'); const other = await createTestAccount();
  const options = { baseURL: 'http://localhost:4000/api/v1/', extraHTTPHeaders: { Origin: 'http://localhost:3000' } };
  const api = await playwright.request.newContext(options); const admin = await playwright.request.newContext(options); const stranger = await playwright.request.newContext(options);
  for (const [client, user] of [[api, student], [admin, staff], [stranger, other]] as const) expect((await client.post('auth/login', { data: { identifier: user.email, password: user.password } })).ok()).toBeTruthy();
  const development = await api.get('practical-cases/persona-sin-documentacion'); expect(development.ok()).toBeTruthy(); expect(await development.text()).not.toContain('modelAnswer');
  const { id } = await (await api.post('practical-cases/persona-sin-documentacion/attempts')).json() as { id: string };
  expect((await stranger.get(`case-attempts/${id}`)).status()).toBe(404);
  expect((await api.patch(`case-attempts/${id}`, { data: { answer: 'Identifico los hechos y explico el fundamento, la competencia, el procedimiento y las garantías. Documento los datos observados y separo las manifestaciones.' } })).ok()).toBeTruthy();
  expect((await api.post(`case-attempts/${id}/submit`)).ok()).toBeTruthy();
  await expect.poll(async () => (await (await api.get(`case-attempts/${id}`)).json()).status, { timeout: 20000 }).toBe('COMPLETED');
  const evaluation = await (await api.get(`case-attempts/${id}`)).json(); expect(evaluation.score).toBe(50); expect(evaluation.evaluation.abstentions[0]).toContain('mock');
  expect((await api.patch(`case-attempts/${id}`, { data: { answer: 'changed' } })).status()).toBe(409);
  expect((await (await api.get('progress')).json()).skills.length).toBe(8);
  const mcq = await (await api.get('practical-cases/metodo-tipo-test')).json(); expect(mcq.data.questions[0].correct).toBeUndefined(); expect(mcq.data.questions[0].explanation).toBeUndefined();
  const mcqAttempt = await (await api.post('practical-cases/metodo-tipo-test/attempts')).json();
  expect((await api.post(`case-attempts/${mcqAttempt.id}/submit`, { data: { answers: { hechos: 0 } } })).ok()).toBeTruthy();
  expect((await (await api.get('error-bank')).json()).total).toBeGreaterThan(0);
  const templates = await (await api.get('exams')).json(); const examId = templates.items[0].id;
  const exam = await (await api.post(`exams/${examId}/start`)).json();
  const examPayload = await (await api.get(`exam-attempts/${exam.id}`)).json(); expect(examPayload.snapshot.data.questions[0].correct).toBeUndefined();
  await api.patch(`exam-attempts/${exam.id}/answers`, { data: { answers: { hechos: 1 } } });
  await api.post(`exam-attempts/${exam.id}/submit`); const result = await (await api.get(`exam-attempts/${exam.id}`)).json(); expect(result.status).toBe('COMPLETED'); expect(result.result.correct).toBe(1);
  expect((await api.patch(`exam-attempts/${exam.id}/answers`, { data: { answers: { hechos: 0 } } })).status()).toBe(409);
  const expired = await (await api.post(`exams/${examId}/start`)).json(); await db.examAttempt.update({ where: { id: expired.id }, data: { expiresAt: new Date(Date.now() - 1000) } });
  expect((await api.patch(`exam-attempts/${expired.id}/answers`, { data: { answers: { hechos: 1 } } })).status()).toBe(409);
  expect((await (await api.get(`exam-attempts/${expired.id}`)).json()).status).toBe('COMPLETED');
  const mixedTemplate = await db.content.create({ data: { kind: 'EXAM', format: 'MIXED', slug: `e2e-mixed-${student.id}`, title: 'Examen mixto de prueba', summary: 'Fixture original de integración', category: 'METODO', body: 'Responde al cuestionario y desarrolla una actuación razonada.', status: 'PUBLISHED', data: { rubric, questions: questions.slice(0, 2) }, sourceAttribution: 'Fixture E2E original' } });
  const mixed = await (await api.post(`exams/${mixedTemplate.id}/start`)).json();
  await api.patch(`exam-attempts/${mixed.id}/answers`, { data: { answers: { hechos: 1, competencia: 1 }, development: 'Expongo los hechos, fundamento la competencia, ordeno el procedimiento y justifico las garantías.' } });
  await api.post(`exam-attempts/${mixed.id}/submit`);
  await expect.poll(async () => (await (await api.get(`exam-attempts/${mixed.id}`)).json()).status, { timeout: 20000 }).toBe('COMPLETED');
  expect((await (await api.get(`exam-attempts/${mixed.id}`)).json()).score).toBe(75);
  await api.post('subscriptions/checkout', { data: { planCode: 'TEMARIO' } }); expect((await api.get('practical-cases/persona-sin-documentacion')).status()).toBe(403); expect((await api.get('theory/metodo-universal')).status()).toBe(200);
  const thread = await (await api.post('support/threads', { data: { subject: 'Duda sobre el método', category: 'SUPUESTO', body: '¿Cómo estructuro mi respuesta?' } })).json();
  expect((await stranger.get(`support/threads/${thread.id}`)).status()).toBe(404);
  await admin.post(`admin/support/${thread.id}/notes`, { data: { body: 'Nota interna reservada para el equipo.' } });
  await admin.post(`admin/support/${thread.id}/messages`, { data: { body: 'Empieza por los hechos y justifica cada actuación.' } });
  const reply = await (await api.get(`support/threads/${thread.id}`)).json(); expect(reply.messages).toHaveLength(2); expect(reply.notes).toBeUndefined(); expect(JSON.stringify(reply)).not.toContain('Nota interna');
  expect((await api.get('admin/users')).status()).toBe(403);
  await admin.post(`admin/users/${student.id}/entitlements`, { data: { module: 'MANUAL_PROFESIONAL' } }); expect((await api.get('manual')).ok()).toBeTruthy();
  const suspend = await admin.patch(`admin/users/${student.id}`, { data: { status: 'SUSPENDED' } }); expect(suspend.ok()).toBeTruthy(); expect((await api.get('auth/me')).status()).toBe(401);
  const audit = await (await admin.get('admin/audit')).json(); expect(audit.total).toBeGreaterThan(0);
  await api.dispose(); await admin.dispose(); await stranger.dispose();
});
test('interfaz de alumno y móvil de 360 px', async ({ page }) => {
  const user = await createTestAccount(); await page.goto('/login'); await page.getByLabel('Email o nombre de usuario').fill(user.email); await page.getByLabel('Contraseña', { exact: true }).fill(user.password); await page.getByRole('button', { name: 'Entrar a mi espacio' }).click(); await expect(page).toHaveURL('/app'); await expect(page.getByRole('heading', { name: 'Hoy es un buen día para avanzar.' })).toBeVisible();
  await page.screenshot({ path: '.local/dashboard-desktop.png', fullPage: true });
  const accessibility = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze(); expect(accessibility.violations).toEqual([]);
  await page.getByRole('link', { name: 'Temario práctico', exact: true }).click(); await page.getByRole('link', { name: 'Método universal de resolución', exact: true }).click(); await page.getByRole('button', { name: 'Marcar como estudiada' }).click(); await expect(page.getByRole('button', { name: 'Ficha estudiada ✓' })).toBeDisabled();
  await page.setViewportSize({ width: 360, height: 780 });
  for (const route of ['/app', '/app/supuestos', '/app/examenes', '/app/soporte', '/app/suscripcion', '/app/cuenta']) { await page.goto(route); await expect(page.locator('h1')).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); }
  await page.goto('/app'); await expect(page.getByRole('heading', { name: 'Hoy es un buen día para avanzar.' })).toBeVisible(); await page.screenshot({ path: '.local/dashboard-mobile.png', fullPage: true });
});
