'use client';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, post } from '../../services/api';
import { PageHeader, ErrorNotice } from '../../components/ui/common';
export function Tutor({ professional = false }: { professional?: boolean }) {
  const [id, setId] = useState(''); const [body, setBody] = useState(''); const client = useQueryClient();
  const conversations = useQuery({ queryKey: ['conversations'], queryFn: () => api<{ id: string; mode: string; createdAt: string }[]>('ai/conversations') });
  const messages = useQuery({ queryKey: ['ai-messages', id], queryFn: () => api<{ id: string; role: string; body: string; createdAt: string }[]>(`ai/conversations/${id}/messages`), enabled: !!id });
  const send = useMutation({ mutationFn: async () => { let currentId = id; if (!currentId) { const c = await post<{ id: string }>('ai/conversations', { mode: professional ? 'PROFESSIONAL_ASSISTANT' : 'STUDY_TUTOR' }); currentId = c.id; setId(c.id); } return post(`ai/conversations/${currentId}/messages`, { body }); }, onSuccess: () => { setBody(''); client.invalidateQueries({ queryKey: ['ai-messages'] }); client.invalidateQueries({ queryKey: ['conversations'] }); } });
  return <><PageHeader eyebrow={professional ? 'CONSULTA CON FUENTES' : 'APRENDER A RAZONAR'} title={professional ? 'Asistente profesional IA' : 'Tutor IA'} description="Una herramienta de estudio. Este canal responde mediante IA; no es una conversación con una persona." /><div className="two-columns"><section className="panel"><ErrorNotice error={send.error ?? messages.error} />{!id && <div className="empty"><h2>Empieza por una duda concreta.</h2><p className="muted">Por ejemplo: ¿cómo organizo las garantías en mi respuesta?</p></div>}{messages.data?.map(m => <div className={`message ${m.role === 'USER' ? 'mine' : ''}`} key={m.id}><small>{m.role === 'USER' ? 'Tú' : 'Tutor IA'} · {new Date(m.createdAt).toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}</small>{m.body}</div>)}<form className="stack" onSubmit={e => { e.preventDefault(); send.mutate(); }}><label>Tu consulta<textarea value={body} onChange={e => setBody(e.target.value)} maxLength={6000} required placeholder="Escribe una duda sobre el método o el caso…" /></label><button className="button" disabled={send.isPending || !body.trim()}>{send.isPending ? 'Consultando…' : 'Consultar al Tutor IA'}</button></form></section><aside className="panel"><h2>Tus conversaciones</h2><button className="button secondary" onClick={() => setId('')}>Nueva consulta</button>{conversations.data?.filter(c => c.mode === (professional ? 'PROFESSIONAL_ASSISTANT' : 'STUDY_TUTOR')).map(c => <button className="list-item" style={{ width: '100%', marginTop: 10 }} key={c.id} onClick={() => setId(c.id)}>Consulta del {new Date(c.createdAt).toLocaleDateString('es-ES')}</button>)}<p className="fine muted" style={{ marginTop: 20 }}>No incluyas datos personales de intervenciones reales. Si falta evidencia jurídica suficiente, la IA debe abstenerse.</p></aside></div></>;
}
