import { skills, type Rubric } from 'shared';
export const rubric: Rubric = skills.map((criterionId, i) => ({ criterionId, weight: [10, 20, 15, 20, 15, 10, 5, 5][i] }));
export const units = [
  { slug: 'metodo-universal', title: 'Método universal de resolución', category: 'METODO', summary: 'Del enunciado a una respuesta ordenada, justificada y evaluable.', body: '## 1. Lee los hechos\nSepara lo observado, las manifestaciones y los datos que faltan.\n\n## 2. Identifica el problema\nFormula las cuestiones que debes resolver antes de proponer medidas.\n\n## 3. Fundamenta\nLocaliza fuentes oficiales vigentes. Relaciona cada medida con su presupuesto y sus límites.\n\n## 4. Ordena la actuación\nExplica competencia, secuencia, garantías y documentación.\n\n## 5. Revisa\nComprueba que ninguna conclusión dependa de un hecho que el enunciado no aporta.\n\n### Error habitual\nCitar normas sin explicar su aplicación al caso.' },
  { slug: 'identificacion', title: 'Identificación de personas', category: 'SEGURIDAD_CIUDADANA', summary: 'Justifica el requerimiento y distingue comprobaciones, límites y garantías.', body: '## Objetivo de estudio\nAnalizar primero el supuesto que habilita la identificación. La ausencia de un documento no sustituye esa justificación.\n\n## Orden de la respuesta\n1. Hechos y finalidad del requerimiento.\n2. Comprobaciones posibles.\n3. Presupuestos de cada actuación.\n4. Proporcionalidad y garantías.\n5. Documentación.\n\n## Refuerzo\nConsulta el artículo 16 de la LO 4/2015 en la fuente oficial y verifica su redacción aplicable. Este material demo está pendiente de revisión jurídica.' },
  { slug: 'vehiculo-sin-seguro', title: 'Vehículo sin seguro obligatorio', category: 'TRAFICO', summary: 'Distingue comprobación, medidas y competencia sancionadora.', body: '## Objetivo de estudio\nEvita mezclar la obligación de asegurar, las posibles medidas sobre el vehículo y la competencia sancionadora.\n\n## Esquema de trabajo\n1. Comprobación fiable.\n2. Norma aplicable y vigencia.\n3. Presupuesto de la medida.\n4. Órgano competente.\n5. Documentación y remisión.\n\n## Fuentes para revisar\nRDL 8/2004 y RDL 6/2015. Comprueba el texto oficial y su aplicación temporal antes de formular una conclusión.' },
  { slug: 'siniestro-vial', title: 'Siniestro vial urbano', category: 'TRAFICO', summary: 'Ordena auxilio, competencia funcional y documentación.', body: '## Método aplicado\nEmpieza por los riesgos y necesidades de asistencia descritos en el enunciado. Distingue la atención inicial de la investigación posterior.\n\n## Documentación\nSepara hechos observados, declaraciones y diligencias. Mantén una cronología clara y deja identificadas las cuestiones pendientes de comprobar.\n\n## Fuente de consulta\nArtículo 53 LO 2/1986; revisar su vigencia y los protocolos autorizados que correspondan.' },
  { slug: 'atestado', title: 'Atestado policial', category: 'PENAL_PROCESAL', summary: 'Objetividad, cronología y trazabilidad en la respuesta escrita.', body: '## Estructura pedagógica\nDescribe el objeto, los hechos conocidos, las actuaciones realizadas y los elementos documentados.\n\n## Revisión\n- Separa observaciones de manifestaciones.\n- Justifica las diligencias propuestas.\n- Evita contradicciones temporales.\n- No inventes resultados de pruebas.\n\nConsulta la Ley de Enjuiciamiento Criminal y las instrucciones vigentes del cuerpo. Esta ficha no sustituye una plantilla oficial.' },
  { slug: 'inspeccion-establecimiento', title: 'Inspección de establecimiento', category: 'POLICIA_ADMINISTRATIVA', summary: 'Actividad, competencia, hechos, acta y remisión.', body: '## Método aplicado\nIdentifica actividad, municipio y norma sectorial. No traslades una ordenanza de un municipio a otro.\n\n## Esquema de respuesta\n1. Datos que faltan para concretar la norma.\n2. Competencia inspectora.\n3. Hechos objetivos y evidencias.\n4. Diferencia entre denuncia, medida provisional y sanción.\n5. Documentación y órgano destinatario.\n\nSi no dispones de la ordenanza vigente, explica qué evidencia necesitas.' }
];
export const questions = [
  ['hechos', '¿Cómo deben tratarse las manifestaciones de un testigo?', ['Como hechos comprobados', 'Separadas de las observaciones directas', 'Omitiéndolas siempre'], 1, 'Distinguir el origen de cada dato mejora la trazabilidad.'],
  ['competencia', '¿Qué debe justificarse antes de proponer una actuación?', ['Solo la sanción', 'La competencia y el presupuesto aplicable', 'La extensión del escrito'], 1, 'La respuesta debe explicar quién actúa y por qué procede la medida.'],
  ['fuentes', 'Falta la ordenanza del municipio del caso. ¿Qué haces?', ['Aplico la de otro municipio', 'Invento una regla habitual', 'Identifico la fuente necesaria y limito la conclusión'], 2, 'Una fuente ajena no sustituye la norma aplicable.'],
  ['documentacion', '¿Qué mejora un relato de actuaciones?', ['Orden cronológico y origen de los datos', 'Repetir todas las normas', 'Añadir hechos que parecen probables'], 0, 'La documentación debe permitir reconstruir los hechos sin inventarlos.'],
  ['garantias', '¿Dónde se explican las garantías?', ['Solo al final si sobra tiempo', 'Junto a cada medida relevante', 'No forman parte del supuesto'], 1, 'Conectar medida, presupuesto y garantía produce una respuesta completa.'],
  ['vigencia', 'Una norma aparece en una base de datos. ¿Basta para afirmar su vigencia?', ['Sí, siempre', 'Solo si el título parece correcto', 'No; hay que comprobar versión, ámbito y fechas'], 2, 'La existencia de un documento no acredita su vigencia.'],
  ['argumentacion', '¿Qué convierte una cita en fundamento de una respuesta?', ['Su relación razonada con los hechos', 'La cantidad de artículos', 'El uso de mayúsculas'], 0, 'Explica la conexión entre el hecho y el presupuesto de la norma.'],
  ['revision', '¿Qué debes revisar antes de entregar?', ['Solo la ortografía', 'Coherencia, competencia, garantías y documentación', 'Que todas las frases sean largas'], 1, 'La revisión final incluye contenido, estructura y precisión.']
].map(([id, prompt, options, correct, explanation]) => ({ id: String(id), prompt: String(prompt), options: options as string[], correct: Number(correct), explanation: String(explanation), concept: String(id), recommendation: 'Revisa Método universal de resolución y vuelve a responder esta cuestión.' }));
