-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'SUPPORT', 'CONTENT_EDITOR', 'ADMIN', 'SUPERADMIN');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED', 'DISABLED');

-- CreateEnum
CREATE TYPE "ContentKind" AS ENUM ('THEORY', 'CASE', 'EXAM', 'MANUAL');

-- CreateEnum
CREATE TYPE "EditorialStatus" AS ENUM ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "AttemptStatus" AS ENUM ('DRAFT', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED');

-- CreateTable
CREATE TABLE "T_PLA_D_USUARIO" (
    "PK_USUARIO" UUID NOT NULL,
    "COD_EMAIL" TEXT NOT NULL,
    "COD_USERNAME" TEXT NOT NULL,
    "DES_NOMBRE" TEXT NOT NULL,
    "COD_PASSWORD_HASH" TEXT NOT NULL,
    "COD_ROL" "Role" NOT NULL DEFAULT 'USER',
    "DES_ESTADO" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "TS_VERIFICACION" TIMESTAMP(3),
    "TS_CONSENTIMIENTO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TXT_PERFIL" JSONB NOT NULL DEFAULT '{}',
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_ULTIMO_ACCESO" TIMESTAMP(3),

    CONSTRAINT "T_PLA_D_USUARIO_pkey" PRIMARY KEY ("PK_USUARIO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_SESION_AUTENTICACION" (
    "PK_SESION" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_TOKEN_HASH" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_EXPIRACION" TIMESTAMP(3) NOT NULL,
    "TS_ULTIMO_USO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_REVOCACION" TIMESTAMP(3),

    CONSTRAINT "T_PLA_F_SESION_AUTENTICACION_pkey" PRIMARY KEY ("PK_SESION")
);

-- CreateTable
CREATE TABLE "T_PLA_F_TOKEN_AUTENTICACION" (
    "PK_TOKEN" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_TOKEN_HASH" TEXT NOT NULL,
    "COD_FINALIDAD" TEXT NOT NULL,
    "TS_EXPIRACION" TIMESTAMP(3) NOT NULL,
    "TS_CONSUMO" TIMESTAMP(3),

    CONSTRAINT "T_PLA_F_TOKEN_AUTENTICACION_pkey" PRIMARY KEY ("PK_TOKEN")
);

-- CreateTable
CREATE TABLE "T_PLA_D_PLAN" (
    "PK_PLAN" UUID NOT NULL,
    "COD_PLAN" TEXT NOT NULL,
    "DES_NOMBRE" TEXT NOT NULL,
    "IMP_PRECIO" INTEGER NOT NULL,
    "COD_MODULOS" TEXT[],
    "FLG_ACTIVO" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "T_PLA_D_PLAN_pkey" PRIMARY KEY ("PK_PLAN")
);

-- CreateTable
CREATE TABLE "T_PLA_F_SUSCRIPCION" (
    "PK_SUSCRIPCION" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "FK_PLAN" UUID NOT NULL,
    "DES_ESTADO" TEXT NOT NULL DEFAULT 'ACTIVE',
    "COD_PROVEEDOR" TEXT NOT NULL,
    "COD_CLIENTE_EXTERNO" TEXT,
    "COD_SUSCRIPCION_EXTERNA" TEXT,
    "TS_FIN_PERIODO" TIMESTAMP(3),
    "TS_EVENTO_PROVEEDOR" TIMESTAMP(3),
    "TS_ACTUALIZACION" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "T_PLA_F_SUSCRIPCION_pkey" PRIMARY KEY ("PK_SUSCRIPCION")
);

-- CreateTable
CREATE TABLE "T_PLA_F_ACCESO_MANUAL" (
    "PK_ACCESO" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_MODULO" TEXT NOT NULL,
    "TS_EXPIRACION" TIMESTAMP(3),
    "TS_REVOCACION" TIMESTAMP(3),
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_ACCESO_MANUAL_pkey" PRIMARY KEY ("PK_ACCESO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_EVENTO_FACTURACION" (
    "PK_EVENTO" UUID NOT NULL,
    "COD_EVENTO_PROVEEDOR" TEXT NOT NULL,
    "COD_TIPO" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_EVENTO_FACTURACION_pkey" PRIMARY KEY ("PK_EVENTO")
);

-- CreateTable
CREATE TABLE "T_PLA_D_CONTENIDO" (
    "PK_CONTENIDO" UUID NOT NULL,
    "COD_TIPO" "ContentKind" NOT NULL,
    "COD_SLUG" TEXT NOT NULL,
    "DES_TITULO" TEXT NOT NULL,
    "DES_RESUMEN" TEXT NOT NULL,
    "COD_CATEGORIA" TEXT NOT NULL,
    "COD_FORMATO" TEXT NOT NULL DEFAULT 'DEVELOPMENT',
    "NUM_DIFICULTAD" INTEGER NOT NULL DEFAULT 1,
    "NUM_MINUTOS" INTEGER NOT NULL DEFAULT 15,
    "DES_ESTADO" "EditorialStatus" NOT NULL DEFAULT 'DRAFT',
    "NUM_VERSION" INTEGER NOT NULL DEFAULT 1,
    "TXT_CONTENIDO" TEXT NOT NULL,
    "TXT_DATOS" JSONB NOT NULL,
    "FLG_DEMO" BOOLEAN NOT NULL DEFAULT true,
    "FLG_GRATIS" BOOLEAN NOT NULL DEFAULT false,
    "COD_ORIGEN" TEXT NOT NULL DEFAULT 'ORIGINAL',
    "DES_ATRIBUCION" TEXT NOT NULL,
    "FK_REVISOR" UUID,
    "TS_REVISION" TIMESTAMP(3),
    "TD_FECHA_VIGENCIA" TIMESTAMP(3),
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_ACTUALIZACION" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "T_PLA_D_CONTENIDO_pkey" PRIMARY KEY ("PK_CONTENIDO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_REVISION_CONTENIDO" (
    "PK_REVISION" UUID NOT NULL,
    "FK_CONTENIDO" UUID NOT NULL,
    "NUM_VERSION" INTEGER NOT NULL,
    "TXT_SNAPSHOT" JSONB NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_REVISION_CONTENIDO_pkey" PRIMARY KEY ("PK_REVISION")
);

-- CreateTable
CREATE TABLE "T_PLA_D_FUENTE_CONOCIMIENTO" (
    "PK_FUENTE" UUID NOT NULL,
    "DES_TITULO" TEXT NOT NULL,
    "COD_URL" TEXT NOT NULL,
    "COD_REFERENCIA" TEXT NOT NULL,
    "COD_TIPO" TEXT NOT NULL,
    "DES_ORGANISMO" TEXT NOT NULL,
    "DES_JURISDICCION" TEXT NOT NULL,
    "DES_ESTADO" TEXT NOT NULL DEFAULT 'REVIEW',
    "NUM_VERSION" INTEGER NOT NULL DEFAULT 1,
    "TD_INICIO_VIGENCIA" TIMESTAMP(3),
    "TD_FIN_VIGENCIA" TIMESTAMP(3),
    "TS_REVISION" TIMESTAMP(3),
    "FK_REVISOR" UUID,
    "COD_CHECKSUM" TEXT NOT NULL,
    "TXT_CONTENIDO" TEXT NOT NULL,

    CONSTRAINT "T_PLA_D_FUENTE_CONOCIMIENTO_pkey" PRIMARY KEY ("PK_FUENTE")
);

-- CreateTable
CREATE TABLE "T_PLA_D_FRAGMENTO_CONOCIMIENTO" (
    "PK_FRAGMENTO" UUID NOT NULL,
    "FK_FUENTE" UUID NOT NULL,
    "DES_SECCION" TEXT NOT NULL,
    "COD_ARTICULO" TEXT NOT NULL,
    "TXT_CONTENIDO" TEXT NOT NULL,
    "TXT_METADATOS" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "T_PLA_D_FRAGMENTO_CONOCIMIENTO_pkey" PRIMARY KEY ("PK_FRAGMENTO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_CONTENIDO_FUENTE" (
    "FK_CONTENIDO" UUID NOT NULL,
    "FK_FUENTE" UUID NOT NULL,

    CONSTRAINT "T_PLA_F_CONTENIDO_FUENTE_pkey" PRIMARY KEY ("FK_CONTENIDO","FK_FUENTE")
);

-- CreateTable
CREATE TABLE "T_PLA_F_INTENTO_SUPUESTO" (
    "PK_INTENTO" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "FK_CONTENIDO" UUID NOT NULL,
    "DES_ESTADO" "AttemptStatus" NOT NULL DEFAULT 'DRAFT',
    "TXT_RESPUESTA" TEXT NOT NULL DEFAULT '',
    "TXT_RESPUESTAS" JSONB NOT NULL DEFAULT '{}',
    "TXT_SNAPSHOT" JSONB NOT NULL,
    "TXT_EVALUACION" JSONB,
    "PCT_NOTA" DOUBLE PRECISION,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_ENTREGA" TIMESTAMP(3),
    "TS_FINALIZACION" TIMESTAMP(3),

    CONSTRAINT "T_PLA_F_INTENTO_SUPUESTO_pkey" PRIMARY KEY ("PK_INTENTO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_INTENTO_EXAMEN" (
    "PK_INTENTO_EXAMEN" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "FK_CONTENIDO" UUID NOT NULL,
    "DES_ESTADO" "AttemptStatus" NOT NULL DEFAULT 'DRAFT',
    "TXT_SNAPSHOT" JSONB NOT NULL,
    "TXT_RESPUESTAS" JSONB NOT NULL DEFAULT '{}',
    "COD_SEED" TEXT NOT NULL,
    "TS_INICIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_EXPIRACION" TIMESTAMP(3) NOT NULL,
    "TS_ENTREGA" TIMESTAMP(3),
    "TXT_RESULTADO" JSONB,
    "PCT_NOTA" DOUBLE PRECISION,

    CONSTRAINT "T_PLA_F_INTENTO_EXAMEN_pkey" PRIMARY KEY ("PK_INTENTO_EXAMEN")
);

-- CreateTable
CREATE TABLE "T_PLA_F_PROGRESO_HABILIDAD" (
    "FK_USUARIO" UUID NOT NULL,
    "COD_HABILIDAD" TEXT NOT NULL,
    "PCT_DOMINIO" DOUBLE PRECISION NOT NULL,
    "NUM_MUESTRAS" INTEGER NOT NULL DEFAULT 1,
    "PCT_ULTIMO_RESULTADO" DOUBLE PRECISION NOT NULL,
    "TS_ACTUALIZACION" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "T_PLA_F_PROGRESO_HABILIDAD_pkey" PRIMARY KEY ("FK_USUARIO","COD_HABILIDAD")
);

-- CreateTable
CREATE TABLE "T_PLA_F_ERROR_ESTUDIO" (
    "PK_ERROR" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_CONCEPTO" TEXT NOT NULL,
    "COD_CATEGORIA" TEXT NOT NULL,
    "COD_ORIGEN" TEXT NOT NULL,
    "DES_ACCION" TEXT NOT NULL,
    "COD_SEVERIDAD" TEXT NOT NULL,
    "NUM_REPETICIONES" INTEGER NOT NULL DEFAULT 1,
    "DES_ESTADO" TEXT NOT NULL DEFAULT 'ACTIVE',
    "TS_ULTIMO_ERROR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_PROXIMO_REPASO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "T_PLA_F_ERROR_ESTUDIO_pkey" PRIMARY KEY ("PK_ERROR")
);

-- CreateTable
CREATE TABLE "T_PLA_F_SESION_ESTUDIO" (
    "PK_ESTUDIO" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "FK_CONTENIDO" UUID NOT NULL,
    "TS_FINALIZACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_SESION_ESTUDIO_pkey" PRIMARY KEY ("PK_ESTUDIO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_FAVORITO" (
    "FK_USUARIO" UUID NOT NULL,
    "FK_CONTENIDO" UUID NOT NULL,

    CONSTRAINT "T_PLA_F_FAVORITO_pkey" PRIMARY KEY ("FK_USUARIO","FK_CONTENIDO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_CONVERSACION_IA" (
    "PK_CONVERSACION" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_MODO" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_CONVERSACION_IA_pkey" PRIMARY KEY ("PK_CONVERSACION")
);

-- CreateTable
CREATE TABLE "T_PLA_F_MENSAJE_IA" (
    "PK_MENSAJE" UUID NOT NULL,
    "FK_CONVERSACION" UUID NOT NULL,
    "COD_ROL" TEXT NOT NULL,
    "TXT_MENSAJE" TEXT NOT NULL,
    "TXT_CITAS" JSONB NOT NULL DEFAULT '[]',
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_MENSAJE_IA_pkey" PRIMARY KEY ("PK_MENSAJE")
);

-- CreateTable
CREATE TABLE "T_PLA_F_CONSUMO_IA" (
    "PK_CONSUMO" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "COD_OPERACION" TEXT NOT NULL,
    "COD_MODELO" TEXT NOT NULL,
    "NUM_TOKENS" INTEGER NOT NULL DEFAULT 0,
    "NUM_LATENCIA" INTEGER NOT NULL,
    "DES_RESULTADO" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_CONSUMO_IA_pkey" PRIMARY KEY ("PK_CONSUMO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_HILO_SOPORTE" (
    "PK_HILO" UUID NOT NULL,
    "FK_USUARIO" UUID NOT NULL,
    "DES_ASUNTO" TEXT NOT NULL,
    "COD_CATEGORIA" TEXT NOT NULL,
    "DES_ESTADO" TEXT NOT NULL DEFAULT 'PENDING_STAFF',
    "FK_RESPONSABLE" UUID,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TS_ACTUALIZACION" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "T_PLA_F_HILO_SOPORTE_pkey" PRIMARY KEY ("PK_HILO")
);

-- CreateTable
CREATE TABLE "T_PLA_F_MENSAJE_SOPORTE" (
    "PK_MENSAJE" UUID NOT NULL,
    "FK_HILO" UUID NOT NULL,
    "FK_REMITENTE" UUID NOT NULL,
    "FLG_EQUIPO" BOOLEAN NOT NULL DEFAULT false,
    "TXT_MENSAJE" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_MENSAJE_SOPORTE_pkey" PRIMARY KEY ("PK_MENSAJE")
);

-- CreateTable
CREATE TABLE "T_PLA_F_NOTA_INTERNA_SOPORTE" (
    "PK_NOTA" UUID NOT NULL,
    "FK_HILO" UUID NOT NULL,
    "FK_AUTOR" UUID NOT NULL,
    "TXT_NOTA" TEXT NOT NULL,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_F_NOTA_INTERNA_SOPORTE_pkey" PRIMARY KEY ("PK_NOTA")
);

-- CreateTable
CREATE TABLE "T_PLA_A_AUDITORIA_ADMIN" (
    "PK_AUDITORIA" UUID NOT NULL,
    "FK_ACTOR" UUID NOT NULL,
    "COD_ACCION" TEXT NOT NULL,
    "COD_ENTIDAD" TEXT NOT NULL,
    "TXT_ANTES" JSONB,
    "TXT_DESPUES" JSONB,
    "TS_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "T_PLA_A_AUDITORIA_ADMIN_pkey" PRIMARY KEY ("PK_AUDITORIA")
);

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_D_USUARIO_COD_EMAIL_key" ON "T_PLA_D_USUARIO"("COD_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_D_USUARIO_COD_USERNAME_key" ON "T_PLA_D_USUARIO"("COD_USERNAME");

-- CreateIndex
CREATE INDEX "T_PLA_D_USUARIO_DES_ESTADO_TS_CREACION_idx" ON "T_PLA_D_USUARIO"("DES_ESTADO", "TS_CREACION");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_SESION_AUTENTICACION_COD_TOKEN_HASH_key" ON "T_PLA_F_SESION_AUTENTICACION"("COD_TOKEN_HASH");

-- CreateIndex
CREATE INDEX "T_PLA_F_SESION_AUTENTICACION_FK_USUARIO_TS_REVOCACION_idx" ON "T_PLA_F_SESION_AUTENTICACION"("FK_USUARIO", "TS_REVOCACION");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_TOKEN_AUTENTICACION_COD_TOKEN_HASH_key" ON "T_PLA_F_TOKEN_AUTENTICACION"("COD_TOKEN_HASH");

-- CreateIndex
CREATE INDEX "T_PLA_F_TOKEN_AUTENTICACION_FK_USUARIO_COD_FINALIDAD_idx" ON "T_PLA_F_TOKEN_AUTENTICACION"("FK_USUARIO", "COD_FINALIDAD");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_D_PLAN_COD_PLAN_key" ON "T_PLA_D_PLAN"("COD_PLAN");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_SUSCRIPCION_FK_USUARIO_key" ON "T_PLA_F_SUSCRIPCION"("FK_USUARIO");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_SUSCRIPCION_COD_CLIENTE_EXTERNO_key" ON "T_PLA_F_SUSCRIPCION"("COD_CLIENTE_EXTERNO");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_SUSCRIPCION_COD_SUSCRIPCION_EXTERNA_key" ON "T_PLA_F_SUSCRIPCION"("COD_SUSCRIPCION_EXTERNA");

-- CreateIndex
CREATE INDEX "T_PLA_F_SUSCRIPCION_FK_USUARIO_DES_ESTADO_idx" ON "T_PLA_F_SUSCRIPCION"("FK_USUARIO", "DES_ESTADO");

-- CreateIndex
CREATE INDEX "T_PLA_F_ACCESO_MANUAL_FK_USUARIO_COD_MODULO_TS_REVOCACION_idx" ON "T_PLA_F_ACCESO_MANUAL"("FK_USUARIO", "COD_MODULO", "TS_REVOCACION");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_EVENTO_FACTURACION_COD_EVENTO_PROVEEDOR_key" ON "T_PLA_F_EVENTO_FACTURACION"("COD_EVENTO_PROVEEDOR");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_D_CONTENIDO_COD_SLUG_key" ON "T_PLA_D_CONTENIDO"("COD_SLUG");

-- CreateIndex
CREATE INDEX "T_PLA_D_CONTENIDO_COD_TIPO_DES_ESTADO_COD_CATEGORIA_idx" ON "T_PLA_D_CONTENIDO"("COD_TIPO", "DES_ESTADO", "COD_CATEGORIA");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_REVISION_CONTENIDO_FK_CONTENIDO_NUM_VERSION_key" ON "T_PLA_F_REVISION_CONTENIDO"("FK_CONTENIDO", "NUM_VERSION");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_D_FUENTE_CONOCIMIENTO_COD_REFERENCIA_key" ON "T_PLA_D_FUENTE_CONOCIMIENTO"("COD_REFERENCIA");

-- CreateIndex
CREATE INDEX "T_PLA_D_FUENTE_CONOCIMIENTO_DES_ESTADO_TD_FIN_VIGENCIA_idx" ON "T_PLA_D_FUENTE_CONOCIMIENTO"("DES_ESTADO", "TD_FIN_VIGENCIA");

-- CreateIndex
CREATE INDEX "T_PLA_D_FRAGMENTO_CONOCIMIENTO_FK_FUENTE_idx" ON "T_PLA_D_FRAGMENTO_CONOCIMIENTO"("FK_FUENTE");

-- CreateIndex
CREATE INDEX "T_PLA_F_INTENTO_SUPUESTO_FK_USUARIO_TS_CREACION_idx" ON "T_PLA_F_INTENTO_SUPUESTO"("FK_USUARIO", "TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_INTENTO_SUPUESTO_DES_ESTADO_idx" ON "T_PLA_F_INTENTO_SUPUESTO"("DES_ESTADO");

-- CreateIndex
CREATE INDEX "T_PLA_F_INTENTO_EXAMEN_FK_USUARIO_TS_INICIO_idx" ON "T_PLA_F_INTENTO_EXAMEN"("FK_USUARIO", "TS_INICIO");

-- CreateIndex
CREATE INDEX "T_PLA_F_INTENTO_EXAMEN_DES_ESTADO_TS_EXPIRACION_idx" ON "T_PLA_F_INTENTO_EXAMEN"("DES_ESTADO", "TS_EXPIRACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_ERROR_ESTUDIO_FK_USUARIO_TS_PROXIMO_REPASO_DES_ESTA_idx" ON "T_PLA_F_ERROR_ESTUDIO"("FK_USUARIO", "TS_PROXIMO_REPASO", "DES_ESTADO");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_ERROR_ESTUDIO_FK_USUARIO_COD_CONCEPTO_key" ON "T_PLA_F_ERROR_ESTUDIO"("FK_USUARIO", "COD_CONCEPTO");

-- CreateIndex
CREATE UNIQUE INDEX "T_PLA_F_SESION_ESTUDIO_FK_USUARIO_FK_CONTENIDO_key" ON "T_PLA_F_SESION_ESTUDIO"("FK_USUARIO", "FK_CONTENIDO");

-- CreateIndex
CREATE INDEX "T_PLA_F_CONVERSACION_IA_FK_USUARIO_TS_CREACION_idx" ON "T_PLA_F_CONVERSACION_IA"("FK_USUARIO", "TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_MENSAJE_IA_FK_CONVERSACION_TS_CREACION_idx" ON "T_PLA_F_MENSAJE_IA"("FK_CONVERSACION", "TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_CONSUMO_IA_FK_USUARIO_TS_CREACION_idx" ON "T_PLA_F_CONSUMO_IA"("FK_USUARIO", "TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_HILO_SOPORTE_DES_ESTADO_TS_ACTUALIZACION_idx" ON "T_PLA_F_HILO_SOPORTE"("DES_ESTADO", "TS_ACTUALIZACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_HILO_SOPORTE_FK_USUARIO_TS_ACTUALIZACION_idx" ON "T_PLA_F_HILO_SOPORTE"("FK_USUARIO", "TS_ACTUALIZACION");

-- CreateIndex
CREATE INDEX "T_PLA_F_MENSAJE_SOPORTE_FK_HILO_TS_CREACION_idx" ON "T_PLA_F_MENSAJE_SOPORTE"("FK_HILO", "TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_A_AUDITORIA_ADMIN_TS_CREACION_idx" ON "T_PLA_A_AUDITORIA_ADMIN"("TS_CREACION");

-- CreateIndex
CREATE INDEX "T_PLA_A_AUDITORIA_ADMIN_COD_ENTIDAD_TS_CREACION_idx" ON "T_PLA_A_AUDITORIA_ADMIN"("COD_ENTIDAD", "TS_CREACION");

-- AddForeignKey
ALTER TABLE "T_PLA_F_SESION_AUTENTICACION" ADD CONSTRAINT "T_PLA_F_SESION_AUTENTICACION_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_TOKEN_AUTENTICACION" ADD CONSTRAINT "T_PLA_F_TOKEN_AUTENTICACION_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_SUSCRIPCION" ADD CONSTRAINT "T_PLA_F_SUSCRIPCION_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_SUSCRIPCION" ADD CONSTRAINT "T_PLA_F_SUSCRIPCION_FK_PLAN_fkey" FOREIGN KEY ("FK_PLAN") REFERENCES "T_PLA_D_PLAN"("PK_PLAN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_ACCESO_MANUAL" ADD CONSTRAINT "T_PLA_F_ACCESO_MANUAL_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_REVISION_CONTENIDO" ADD CONSTRAINT "T_PLA_F_REVISION_CONTENIDO_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_D_FRAGMENTO_CONOCIMIENTO" ADD CONSTRAINT "T_PLA_D_FRAGMENTO_CONOCIMIENTO_FK_FUENTE_fkey" FOREIGN KEY ("FK_FUENTE") REFERENCES "T_PLA_D_FUENTE_CONOCIMIENTO"("PK_FUENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_CONTENIDO_FUENTE" ADD CONSTRAINT "T_PLA_F_CONTENIDO_FUENTE_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_CONTENIDO_FUENTE" ADD CONSTRAINT "T_PLA_F_CONTENIDO_FUENTE_FK_FUENTE_fkey" FOREIGN KEY ("FK_FUENTE") REFERENCES "T_PLA_D_FUENTE_CONOCIMIENTO"("PK_FUENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_INTENTO_SUPUESTO" ADD CONSTRAINT "T_PLA_F_INTENTO_SUPUESTO_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_INTENTO_SUPUESTO" ADD CONSTRAINT "T_PLA_F_INTENTO_SUPUESTO_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_INTENTO_EXAMEN" ADD CONSTRAINT "T_PLA_F_INTENTO_EXAMEN_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_INTENTO_EXAMEN" ADD CONSTRAINT "T_PLA_F_INTENTO_EXAMEN_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_PROGRESO_HABILIDAD" ADD CONSTRAINT "T_PLA_F_PROGRESO_HABILIDAD_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_ERROR_ESTUDIO" ADD CONSTRAINT "T_PLA_F_ERROR_ESTUDIO_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_SESION_ESTUDIO" ADD CONSTRAINT "T_PLA_F_SESION_ESTUDIO_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_SESION_ESTUDIO" ADD CONSTRAINT "T_PLA_F_SESION_ESTUDIO_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_FAVORITO" ADD CONSTRAINT "T_PLA_F_FAVORITO_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_FAVORITO" ADD CONSTRAINT "T_PLA_F_FAVORITO_FK_CONTENIDO_fkey" FOREIGN KEY ("FK_CONTENIDO") REFERENCES "T_PLA_D_CONTENIDO"("PK_CONTENIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_CONVERSACION_IA" ADD CONSTRAINT "T_PLA_F_CONVERSACION_IA_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_MENSAJE_IA" ADD CONSTRAINT "T_PLA_F_MENSAJE_IA_FK_CONVERSACION_fkey" FOREIGN KEY ("FK_CONVERSACION") REFERENCES "T_PLA_F_CONVERSACION_IA"("PK_CONVERSACION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_HILO_SOPORTE" ADD CONSTRAINT "T_PLA_F_HILO_SOPORTE_FK_USUARIO_fkey" FOREIGN KEY ("FK_USUARIO") REFERENCES "T_PLA_D_USUARIO"("PK_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_MENSAJE_SOPORTE" ADD CONSTRAINT "T_PLA_F_MENSAJE_SOPORTE_FK_HILO_fkey" FOREIGN KEY ("FK_HILO") REFERENCES "T_PLA_F_HILO_SOPORTE"("PK_HILO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "T_PLA_F_NOTA_INTERNA_SOPORTE" ADD CONSTRAINT "T_PLA_F_NOTA_INTERNA_SOPORTE_FK_HILO_fkey" FOREIGN KEY ("FK_HILO") REFERENCES "T_PLA_F_HILO_SOPORTE"("PK_HILO") ON DELETE RESTRICT ON UPDATE CASCADE;
