import { Controller, Get, Patch, Post, Param, Query, Body, Req, UseGuards, ForbiddenException, NotFoundException, BadRequestException } from '@nestjs/common';
import { z } from 'zod';
import { idSchema, pageSchema, roles, modules } from 'shared';
import { AuthGuard, RolesGuard, Roles, type AuthRequest } from '../../common/guards/auth.guard';
import { db } from '../../database/prisma';
const userSelect = { id: true, name: true, username: true, email: true, role: true, status: true, createdAt: true, verifiedAt: true, lastAccessAt: true, profile: true, subscription: { include: { plan: true } } } as const;
@Controller('admin') @UseGuards(AuthGuard, RolesGuard) @Roles('ADMIN', 'SUPERADMIN')
export class AdminUsersController {
  @Get('users') async list(@Query() input: unknown) { const q = pageSchema.extend({ role: z.enum(roles).optional() }).parse(input); const where = { ...(q.q ? { OR: [{ name: { contains: q.q, mode: 'insensitive' as const } }, { email: { contains: q.q, mode: 'insensitive' as const } }, { username: { contains: q.q, mode: 'insensitive' as const } }] } : {}), ...(q.status ? { status: z.enum(['ACTIVE', 'SUSPENDED', 'DISABLED']).parse(q.status) } : {}), ...(q.role ? { role: q.role } : {}) }; const [items, total] = await Promise.all([db.user.findMany({ where, select: userSelect, take: q.limit, skip: (q.page - 1) * q.limit, orderBy: { createdAt: 'desc' } }), db.user.count({ where })]); return { items, total, page: q.page, limit: q.limit }; }
  @Get('users/:id') async get(@Param('id') id: string) { const user = await db.user.findUnique({ where: { id: idSchema.parse(id) }, select: { ...userSelect, entitlements: true } }); if (!user) throw new NotFoundException(); return user; }
  @Patch('users/:id') async update(@Param('id') id: string, @Req() r: AuthRequest, @Body() input: unknown) {
    const data = z.object({ status: z.enum(['ACTIVE', 'SUSPENDED', 'DISABLED']).optional(), role: z.enum(roles).optional() }).strict().refine(v => v.status || v.role).parse(input); idSchema.parse(id);
    return db.$transaction(async tx => {
      const before = await tx.user.findUniqueOrThrow({ where: { id }, select: { status: true, role: true } });
      if (id === r.user.id) throw new BadRequestException({ code: 'SELF_CHANGE_DENIED', message: 'No puedes cambiar tu propio rol o estado.' });
      if ((before.role === 'SUPERADMIN' || before.role === 'ADMIN' || data.role === 'ADMIN' || data.role === 'SUPERADMIN') && r.user.role !== 'SUPERADMIN') throw new ForbiddenException();
      const after = await tx.user.update({ where: { id }, data, select: userSelect });
      if (data.status && data.status !== 'ACTIVE' || data.role) await tx.authSession.updateMany({ where: { userId: id }, data: { revokedAt: new Date() } });
      await tx.adminAuditLog.create({ data: { actorId: r.user.id, action: 'USER_UPDATE', entityId: id, before, after: data } }); return after;
    });
  }
  @Post('users/:id/revoke-sessions') async revoke(@Param('id') id: string, @Req() r: AuthRequest) { idSchema.parse(id); const target = await db.user.findUniqueOrThrow({ where: { id } }); if (['ADMIN', 'SUPERADMIN'].includes(target.role) && r.user.role !== 'SUPERADMIN') throw new ForbiddenException(); await db.$transaction([db.authSession.updateMany({ where: { userId: id }, data: { revokedAt: new Date() } }), db.adminAuditLog.create({ data: { actorId: r.user.id, action: 'SESSIONS_REVOKED', entityId: id } })]); return { ok: true }; }
  @Post('users/:id/entitlements') async grant(@Param('id') id: string, @Req() r: AuthRequest, @Body() input: unknown) { idSchema.parse(id); const data = z.object({ module: z.enum(modules), expiresAt: z.iso.datetime().optional() }).strict().parse(input); const expiresAt = data.expiresAt ? new Date(data.expiresAt) : null; if (expiresAt && expiresAt <= new Date()) throw new BadRequestException(); return db.$transaction(async tx => { const grant = await tx.manualEntitlement.create({ data: { userId: id, module: data.module, expiresAt } }); await tx.adminAuditLog.create({ data: { actorId: r.user.id, action: 'ENTITLEMENT_GRANTED', entityId: id, after: { grantId: grant.id, module: data.module, expiresAt: data.expiresAt ?? null } } }); return grant; }); }
  @Post('users/:id/entitlements/:grantId/revoke') async ungrant(@Param('id') id: string, @Param('grantId') grantId: string, @Req() r: AuthRequest) { idSchema.parse(id); idSchema.parse(grantId); await db.$transaction([db.manualEntitlement.updateMany({ where: { id: grantId, userId: id }, data: { revokedAt: new Date() } }), db.adminAuditLog.create({ data: { actorId: r.user.id, action: 'ENTITLEMENT_REVOKED', entityId: id, after: { grantId } } })]); return { ok: true }; }
  @Get('audit') async audit(@Query() input: unknown) { const q = pageSchema.parse(input); const [items, total] = await Promise.all([db.adminAuditLog.findMany({ orderBy: { createdAt: 'desc' }, take: q.limit, skip: (q.page - 1) * q.limit }), db.adminAuditLog.count()]); return { items, total, page: q.page, limit: q.limit }; }
  @Get('metrics') async metrics() { const [users, active7, active30, subscriptions, attempts, exams, pendingSupport, review, usage] = await Promise.all([db.user.count(), db.user.count({ where: { lastAccessAt: { gte: new Date(Date.now() - 7 * 86400000) } } }), db.user.count({ where: { lastAccessAt: { gte: new Date(Date.now() - 30 * 86400000) } } }), db.subscription.count({ where: { status: 'ACTIVE', plan: { code: { not: 'GRATIS' } } } }), db.caseAttempt.count({ where: { status: 'COMPLETED' } }), db.examAttempt.count({ where: { status: 'COMPLETED' } }), db.supportThread.count({ where: { status: 'PENDING_STAFF' } }), db.content.count({ where: { status: 'REVIEW' } }), db.aiUsageRecord.count()]); return { users, active7, active30, subscriptions, attempts, exams, pendingSupport, review, usage }; }
  @Get('subscriptions') async subscriptions(@Query() input: unknown) { const q = pageSchema.parse(input); const [items, total] = await Promise.all([db.subscription.findMany({ include: { user: { select: { name: true, email: true } }, plan: true }, orderBy: { updatedAt: 'desc' }, take: q.limit, skip: (q.page - 1) * q.limit }), db.subscription.count()]); return { items, total, page: q.page, limit: q.limit }; }
  @Patch('plans/:id') async plan(@Param('id') id: string, @Req() r: AuthRequest, @Body() input: unknown) { idSchema.parse(id); const data = z.object({ priceCents: z.number().int().min(0).max(100000), active: z.boolean() }).strict().parse(input); return db.$transaction(async tx => { const before = await tx.plan.findUniqueOrThrow({ where: { id } }); const after = await tx.plan.update({ where: { id }, data }); await tx.adminAuditLog.create({ data: { actorId: r.user.id, action: 'PLAN_UPDATED', entityId: id, before: { priceCents: before.priceCents, active: before.active }, after: data } }); return after; }); }
}
