'use client';
import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { loginSchema, registerSchema, emailSchema, resetSchema } from 'shared';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { post } from '../../services/api';
import { ErrorNotice } from '../../components/ui/common';
type Mode = 'login' | 'registro' | 'recuperar-password' | 'verificar-email';
export function AuthForm({ mode }: { mode: Mode }) {
  const [token, setToken] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState<Error | null>(null); const [resendEmail, setResendEmail] = useState(''); const [resending, setResending] = useState(false); const router = useRouter();
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('token') ?? ''; setToken(value); if (value) window.history.replaceState(null, '', window.location.pathname); }, []);
  const schema = mode === 'registro' ? registerSchema : mode === 'login' ? loginSchema : token ? resetSchema : emailSchema;
  const { register, handleSubmit, formState: { isSubmitting, errors }, setValue } = useForm<Record<string, unknown>>({ resolver: zodResolver(schema as z.ZodType<Record<string, unknown>, Record<string, unknown>>) });
  useEffect(() => { if (token) setValue('token', token); }, [token, setValue]);
  const send = async (data: Record<string, unknown>) => { setError(null); try { const path = mode === 'registro' ? 'register' : mode === 'login' ? 'login' : token ? 'reset-password' : 'forgot-password'; const result = await post<{ message?: string }>(`auth/${path}`, data); if (mode === 'login') { router.push('/app'); router.refresh(); } else setMessage(result.message ?? 'Solicitud completada.'); } catch (e) { setError(e as Error); } };
  if (mode === 'verificar-email') return <div><ErrorNotice error={error} />{message ? <><p role="status">{message}</p><Link className="button" href="/login">Iniciar sesión</Link></> : <><p>Confirma tu email para activar tu espacio de estudio.</p>{token && <button className="button" disabled={resending} onClick={async () => { setResending(true); try { const res = await post<{ message: string }>('auth/verify-email', { token }); setMessage(res.message); } catch (e) { setError(e as Error); } finally { setResending(false); } }}>Verificar mi email</button>}<form method="post" className="stack" style={{ marginTop: 20 }} onSubmit={async e => { e.preventDefault(); setResending(true); try { const res = await post<{ message: string }>('auth/resend-verification', { email: resendEmail }); setMessage(res.message); } catch (e) { setError(e as Error); } finally { setResending(false); } }}><label>Email para un nuevo enlace<input type="email" value={resendEmail} onChange={e => setResendEmail(e.target.value)} required /></label><button className="button secondary" disabled={resending}>Reenviar verificación</button></form></>}</div>;
  if (message) return <div className="stack"><p className="notice success" role="status">{message}</p><Link href="/login">Volver a iniciar sesión</Link></div>;
  return <form method="post" className="stack" onSubmit={handleSubmit(send)} noValidate><ErrorNotice error={error} />{mode === 'registro' && <><label>Nombre<input autoComplete="name" {...register('name')} /></label><label>Nombre de usuario<input autoComplete="username" {...register('username')} /></label></>}{mode === 'login' ? <label>Email o nombre de usuario<input autoComplete="username" {...register('identifier')} /></label> : !token && <label>Email<input type="email" autoComplete="email" {...register('email')} /></label>}{(mode === 'login' || mode === 'registro' || !!token) && <label>{token ? 'Nueva contraseña' : 'Contraseña'}<input type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} {...register('password')} />{mode !== 'login' && <small>Al menos 12 caracteres.</small>}</label>}{mode === 'registro' && <><label className="check"><input type="checkbox" {...register('terms')} /><span>Acepto los <Link href="/legal/terminos">términos de uso</Link>.</span></label><label className="check"><input type="checkbox" {...register('privacy')} /><span>He leído la <Link href="/legal/privacidad">política de privacidad</Link>.</span></label></>}{Object.keys(errors).length > 0 && <p role="alert" className="field-error">Revisa los campos. Comprueba el email, la contraseña y las casillas de aceptación.</p>}<button className="button" disabled={isSubmitting}>{isSubmitting ? 'Un momento…' : mode === 'login' ? 'Entrar a mi espacio' : mode === 'registro' ? 'Crear mi cuenta' : token ? 'Guardar nueva contraseña' : 'Enviar enlace de recuperación'}</button>{mode === 'login' && <><Link href="/recuperar-password">He olvidado mi contraseña</Link><p className="muted">¿Primera vez aquí? <Link href="/registro">Crea tu cuenta</Link></p></>}</form>;
}
