'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, post, patch } from '../../services/api';
import type { Page } from '../../types/api';
import { PageHeader, ErrorNotice, Loading, Empty } from '../../components/ui/common';
const statuses: Record<string, string> = { OPEN: 'Abierto', PENDING_STAFF: 'Esperando al equipo', PENDING_USER: 'Tienes una respuesta', CLOSED: 'Cerrado' };
interface Thread { id: string; subject: string; category: string; status: string; updatedAt: string; assignedName?: string; responseHours: number; messages: { id: string; body: string; staff: boolean; createdAt: string }[]; notes?: { id: string; body: string }[]; }
export function SupportList({ admin = false }: { admin?: boolean }) {
  const [open, setOpen] = useState(false); const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [category, setCategory] = useState('SUPUESTO'); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const router = useRouter(); const endpoint = admin ? 'admin/support' : 'support/threads';
  const query = useQuery({ queryKey: [endpoint, status, page], queryFn: () => api<Page<Thread> & { responseHours: number }>(`${endpoint}?page=${page}${status ? `&status=${status}` : ''}`), refetchInterval: 20000 });
  const create = useMutation({ mutationFn: () => post<{ id: string }>('support/threads', { subject, body, category }), onSuccess: d => router.push(`/app/soporte/${d.id}`) });
  return <><PageHeader eyebrow="CONVERSACIONES CON PERSONAS" title={admin ? 'Bandeja del equipo' : 'Consulta al equipo'} description={`Cuéntanos tu duda. Tiempo orientativo de respuesta: ${query.data?.responseHours ?? '—'} horas.`} action={!admin && <button className="button" onClick={() => setOpen(!open)}>{open ? 'Cerrar formulario' : 'Nueva consulta'}</button>} /><ErrorNotice error={query.error ?? create.error} />{open && <form className="panel stack" style={{ marginBottom: 22 }} onSubmit={e => { e.preventDefault(); create.mutate(); }}><label>Asunto<input value={subject} onChange={e => setSubject(e.target.value)} minLength={3} maxLength={150} required /></label><label>Categoría<select value={category} onChange={e => setCategory(e.target.value)}>{['SUPUESTO', 'TEORIA', 'EXAMEN', 'FACTURACION', 'TECNICO', 'OTRO'].map(x => <option key={x}>{x}</option>)}</select></label><label>Tu mensaje<textarea value={body} onChange={e => setBody(e.target.value)} maxLength={6000} required /></label><button className="button" disabled={create.isPending}>Enviar consulta al equipo</button></form>}<div className="filters"><select aria-label="Estado de conversaciones" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">Todos los estados</option>{Object.entries(statuses).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></div>{query.isPending && <Loading />}{query.data?.total === 0 && <Empty title="Tu bandeja está vacía" description="Las consultas y respuestas del equipo aparecerán aquí." />}<div className="list">{query.data?.items.map(t => <Link href={`${admin ? '/admin' : '/app'}/soporte/${t.id}`} className="list-item" key={t.id}><div><span className="tag">{statuses[t.status]}</span><h3>{t.subject}</h3><p>{t.category} · {new Date(t.updatedAt).toLocaleDateString('es-ES')}</p></div><span>→</span></Link>)}</div>{query.data && query.data.total > 20 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page}</span><button disabled={page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div>}</>;
}
export function SupportThread({ id, admin = false }: { id: string; admin?: boolean }) {
  const endpoint = `${admin ? 'admin/support' : 'support/threads'}/${id}`; const [body, setBody] = useState(''); const [note, setNote] = useState(false); const client = useQueryClient();
  const query = useQuery({ queryKey: [endpoint], queryFn: () => api<Thread>(endpoint), refetchInterval: 10000 });
  const send = useMutation({ mutationFn: () => post(`${endpoint}/${admin && note ? 'notes' : 'messages'}`, { body }), onSuccess: () => { setBody(''); client.invalidateQueries({ queryKey: [endpoint] }); } });
  const state = useMutation({ mutationFn: (status: string) => patch(endpoint, { status }), onSuccess: () => client.invalidateQueries({ queryKey: [endpoint] }) });
  if (query.isPending) return <Loading />; if (!query.data) return <ErrorNotice error={query.error} />; const t = query.data;
  return <><Link href={admin ? '/admin/soporte' : '/app/soporte'}>← Conversaciones</Link><PageHeader eyebrow="CONSULTA AL EQUIPO · CHAT HUMANO" title={t.subject} description={`${statuses[t.status]} · ${t.assignedName ? `Responsable: ${t.assignedName}` : 'Pendiente de asignación'} · Respuesta orientativa: ${t.responseHours} h`} action={<button className="button secondary" disabled={state.isPending} onClick={() => state.mutate(t.status === 'CLOSED' ? 'PENDING_STAFF' : 'CLOSED')}>{t.status === 'CLOSED' ? 'Reabrir conversación' : 'Cerrar conversación'}</button>} /><section className="panel"><ErrorNotice error={send.error ?? state.error} />{t.messages.map(m => <div className={`message ${m.staff ? '' : 'mine'}`} key={m.id}><small>{m.staff ? 'Equipo SP Local IA' : 'Alumno'} · {new Date(m.createdAt).toLocaleString('es-ES')}</small>{m.body}</div>)}{admin && t.notes?.map(n => <div className="notice" key={n.id}>Nota interna: {n.body}</div>)}{t.status !== 'CLOSED' && <form className="stack" onSubmit={e => { e.preventDefault(); send.mutate(); }}><label>{admin && note ? 'Nota interna (no visible para el alumno)' : 'Nuevo mensaje'}<textarea value={body} onChange={e => setBody(e.target.value)} required maxLength={6000} /></label>{admin && <label className="check"><input type="checkbox" checked={note} onChange={e => setNote(e.target.checked)} />Guardar como nota interna</label>}<button className="button" disabled={send.isPending || !body.trim()}>{admin && note ? 'Guardar nota interna' : 'Enviar mensaje'}</button></form>}</section></>;
}
