'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, patch } from '../../services/api';
import type { User, Page, Plan } from '../../types/api';
import { PageHeader, ErrorNotice, Loading } from '../../components/ui/common';
import { AdminUsers } from './admin-users';
import { AdminContent } from './admin-content';
import { SupportList, SupportThread } from '../support/support';
export function AdminRouter({ segments }: { segments: string[] }) {
  const me = useQuery({ queryKey: ['me'], queryFn: () => api<User>('auth/me') });
  if (me.isPending) return <Loading />; if (!me.data || me.data.role === 'USER') return <p className="notice error">No tienes acceso a la administración.</p>;
  const [section, id] = segments;
  return <><nav className="tabs" aria-label="Administración"><Link href="/admin">Resumen</Link><Link href="/admin/usuarios">Usuarios</Link><Link href="/admin/contenido/temario">Temario</Link><Link href="/admin/contenido/supuestos">Supuestos</Link><Link href="/admin/contenido/examenes">Exámenes</Link><Link href="/admin/contenido/manual">Manual</Link><Link href="/admin/contenido/fuentes">Fuentes</Link><Link href="/admin/soporte">Soporte</Link><Link href="/admin/suscripciones">Suscripciones</Link><Link href="/admin/auditoria">Auditoría</Link></nav>{section === 'usuarios' ? <AdminUsers id={id} /> : section === 'contenido' ? id === 'fuentes' ? <Sources /> : <AdminContent key={id} section={id} /> : section === 'soporte' ? id ? <SupportThread id={id} admin /> : <SupportList admin /> : section === 'suscripciones' ? <Subscriptions /> : section === 'auditoria' ? <Audit /> : !section ? <Overview /> : <p>Página no encontrada.</p>}</>;
}
function Overview() {
  const query = useQuery({ queryKey: ['admin-metrics'], queryFn: () => api<Record<string, number>>('admin/metrics') }); const labels: Record<string, string> = { users: 'Usuarios registrados', active7: 'Activos en 7 días', active30: 'Activos en 30 días', subscriptions: 'Suscripciones con módulos', attempts: 'Supuestos completados', exams: 'Exámenes completados', pendingSupport: 'Consultas pendientes', review: 'Contenidos en revisión', usage: 'Operaciones IA' };
  return <><PageHeader eyebrow="ADMINISTRACIÓN" title="El estado de la plataforma" description="Actividad registrada en la base de datos." /><ErrorNotice error={query.error} /><div className="three-columns">{Object.entries(query.data ?? {}).map(([k, v]) => <section className="panel stat" key={k}><strong>{v}</strong><small>{labels[k] ?? k}</small></section>)}</div></>;
}
interface Source { id: string; title: string; status: string; url: string; body: string; validFrom: string | null; validTo: string | null; version: number; }
function Sources() {
  const [selected, setSelected] = useState<Source | null>(null); const query = useQuery({ queryKey: ['sources'], queryFn: () => api<Page<Source>>('admin/sources') });
  if (selected) return <SourceEditor source={selected} close={() => setSelected(null)} />;
  return <><PageHeader title="Fuentes normativas" description="Solo las fuentes aprobadas, revisadas y vigentes alimentan las respuestas de IA." /><ErrorNotice error={query.error} /><div className="list">{query.data?.items.map(s => <div className="list-item" key={s.id}><div><h3>{s.title}</h3><p>{s.status} · Versión {s.version}</p><a href={s.url} target="_blank" rel="noreferrer">Consultar fuente oficial</a></div><button className="button secondary" onClick={() => setSelected(s)}>Revisar</button></div>)}</div></>;
}
function SourceEditor({ source, close }: { source: Source; close: () => void }) {
  const [body, setBody] = useState(source.body); const [status, setStatus] = useState(source.status); const [article, setArticle] = useState(''); const [validTo, setValidTo] = useState(source.validTo?.slice(0, 10) ?? ''); const client = useQueryClient();
  const save = useMutation({ mutationFn: () => patch(`admin/sources/${source.id}`, { body, status, article, validFrom: source.validFrom, validTo: validTo ? new Date(validTo).toISOString() : null }), onSuccess: () => { client.invalidateQueries({ queryKey: ['sources'] }); close(); } });
  return <form className="panel stack" onSubmit={e => { e.preventDefault(); save.mutate(); }}><h1>{source.title}</h1><a href={source.url} target="_blank" rel="noreferrer">Abrir texto oficial</a><ErrorNotice error={save.error} /><p className="notice">Aprobar acredita que has comprobado el texto y su vigencia. Expirar una fuente devuelve a revisión los contenidos vinculados.</p><label>Estado<select value={status} onChange={e => setStatus(e.target.value)}>{['DRAFT', 'REVIEW', 'APPROVED', 'EXPIRED', 'REJECTED'].map(s => <option key={s}>{s}</option>)}</select></label><label>Artículo o sección revisada<input value={article} onChange={e => setArticle(e.target.value)} required /></label><label>Texto revisado<textarea value={body} onChange={e => setBody(e.target.value)} minLength={20} required /></label><label>Fin de vigencia (si se conoce)<input type="date" value={validTo} onChange={e => setValidTo(e.target.value)} /></label><div className="actions"><button className="button" disabled={save.isPending}>Guardar revisión</button><button type="button" className="button secondary" onClick={close}>Volver</button></div></form>;
}
function Audit() {
  const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['audit', page], queryFn: () => api<Page<{ id: string; action: string; actorId: string; entityId: string; createdAt: string }>>(`admin/audit?page=${page}`) });
  return <><PageHeader title="Auditoría" description="Registro de acciones administrativas sensibles." /><ErrorNotice error={query.error} /><div className="panel table-scroll"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Actor</th><th>Entidad</th></tr></thead><tbody>{query.data?.items.map(a => <tr key={a.id}><td>{new Date(a.createdAt).toLocaleString('es-ES')}</td><td>{a.action}</td><td><code>{a.actorId}</code></td><td><code>{a.entityId}</code></td></tr>)}</tbody></table></div><div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page}</span><button className="button secondary" disabled={!query.data || page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div></>;
}
function Subscriptions() {
  const [page, setPage] = useState(1); const plans = useQuery({ queryKey: ['plans'], queryFn: () => api<Plan[]>('plans') }); const query = useQuery({ queryKey: ['admin-subscriptions', page], queryFn: () => api<Page<{ id: string; userId: string; status: string; provider: string; user: { name: string; email: string }; plan: Plan }>>(`admin/subscriptions?page=${page}`) });
  return <><PageHeader title="Suscripciones y planes" description="Los precios mostrados y los permisos se gestionan en el servidor. Los precios de Stripe se configuran por separado." /><ErrorNotice error={query.error ?? plans.error} /><div className="panel table-scroll"><table><thead><tr><th>Usuario</th><th>Plan</th><th>Estado</th><th>Proveedor</th></tr></thead><tbody>{query.data?.items.map(s => <tr key={s.id}><td><Link href={`/admin/usuarios/${s.userId}`}>{s.user.name}</Link><br />{s.user.email}</td><td>{s.plan.name}</td><td>{s.status}</td><td>{s.provider}</td></tr>)}</tbody></table></div><div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page}</span><button className="button secondary" disabled={!query.data || page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div><div className="three-columns">{plans.data?.map(p => <PlanEditor key={p.id} plan={p} />)}</div></>;
}
function PlanEditor({ plan }: { plan: Plan }) { const [price, setPrice] = useState(String(plan.priceCents / 100)); const [active, setActive] = useState(plan.active); const save = useMutation({ mutationFn: () => patch(`admin/plans/${plan.id}`, { priceCents: Math.round(Number(price) * 100), active }) }); return <form className="panel stack" onSubmit={e => { e.preventDefault(); save.mutate(); }}><h3>{plan.name}</h3><ErrorNotice error={save.error} /><label>Precio mostrado (€)<input type="number" min="0" max="1000" step="0.01" value={price} onChange={e => setPrice(e.target.value)} required /></label><label className="check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} />Plan activo</label><button className="button secondary" disabled={save.isPending}>Guardar plan</button>{save.isSuccess && <p role="status">Plan guardado.</p>}</form>; }
