'use client';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { contentDataSchema, categories, categoryLabels } from 'shared';
import { api, patch, post } from '../../services/api';
import type { Page, ContentSummary } from '../../types/api';
import { PageHeader, ErrorNotice, Loading } from '../../components/ui/common';
interface EditableContent extends ContentSummary { body: string; data: unknown; }
const kindMap: Record<string, string> = { temario: 'THEORY', supuestos: 'CASE', examenes: 'EXAM', manual: 'MANUAL' };
export function AdminContent({ section }: { section: string }) {
  const [selected, setSelected] = useState<EditableContent | null>(null); const [page, setPage] = useState(1); const [q, setQ] = useState(''); const [create, setCreate] = useState(false); const kind = kindMap[section] ?? 'THEORY'; const client = useQueryClient();
  const query = useQuery({ queryKey: ['admin-content', kind, page, q], queryFn: () => api<Page<EditableContent>>(`admin/content?kind=${kind}&page=${page}&q=${encodeURIComponent(q)}`) });
  const created = () => { setCreate(false); client.invalidateQueries({ queryKey: ['admin-content'] }); };
  if (selected) return <ContentEditor key={selected.id} content={selected} onClose={() => setSelected(null)} />;
  if (create) return <ContentCreator kind={kind} onClose={created} />;
  return <><PageHeader title={`Contenido · ${section}`} description="Los cambios generan una nueva versión; los intentos anteriores conservan su copia." action={<button className="button" onClick={() => setCreate(true)}>Crear borrador</button>} /><input aria-label="Buscar contenido editorial" value={q} onChange={e => { setQ(e.target.value); setPage(1); }} placeholder="Buscar por título…" /><ErrorNotice error={query.error} />{query.isPending && <Loading />}<div className="list" style={{ marginTop: 20 }}>{query.data?.items.map(c => <article className="list-item" key={c.id}><div><span className="tag">{c.status} · v{c.version}</span><h3>{c.title}</h3></div><button className="button secondary" onClick={() => setSelected(c)}>Editar</button></article>)}</div><div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page}</span><button className="button secondary" disabled={!query.data || page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div></>;
}
function ContentCreator({ kind, onClose }: { kind: string; onClose: () => void }) {
  const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [summary, setSummary] = useState(''); const [body, setBody] = useState(''); const [category, setCategory] = useState<string>(categories[0]);
  const create = useMutation({ mutationFn: () => post('admin/content', { kind, title, slug, summary, body, category }), onSuccess: onClose });
  return <form className="panel stack" onSubmit={e => { e.preventDefault(); create.mutate(); }}><h1>Nuevo borrador</h1><ErrorNotice error={create.error} /><label>Título<input value={title} onChange={e => setTitle(e.target.value)} required minLength={3} /></label><label>Identificador de URL<input value={slug} onChange={e => setSlug(e.target.value)} pattern="[a-z0-9-]+" required placeholder="identificacion-caso-urbano" /></label><label>Resumen<input value={summary} onChange={e => setSummary(e.target.value)} required minLength={5} /></label><label>Categoría<select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <option value={c} key={c}>{categoryLabels[c]}</option>)}</select></label><label>Contenido<textarea value={body} onChange={e => setBody(e.target.value)} required minLength={10} /></label><div className="actions"><button className="button" disabled={create.isPending}>Crear borrador</button><button type="button" className="button secondary" onClick={onClose}>Volver</button></div></form>;
}
function ContentEditor({ content, onClose }: { content: EditableContent; onClose: () => void }) {
  const [title, setTitle] = useState(content.title); const [summary, setSummary] = useState(content.summary); const [body, setBody] = useState(content.body); const [status, setStatus] = useState(content.status); const [data, setData] = useState(contentDataSchema.parse(content.data)); const client = useQueryClient();
  const save = useMutation({ mutationFn: () => patch(`admin/content/${content.id}`, { title, summary, body, status, category: content.category, minutes: content.minutes, difficulty: content.difficulty, data, version: content.version }), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin-content'] }); onClose(); } });
  return <form className="panel stack" onSubmit={e => { e.preventDefault(); save.mutate(); }}><PageHeader title="Editar contenido" description={`Versión ${content.version}`} /><ErrorNotice error={save.error} /><label>Título<input value={title} onChange={e => setTitle(e.target.value)} required /></label><label>Resumen<input value={summary} onChange={e => setSummary(e.target.value)} required /></label><label>Estado editorial<select value={status} onChange={e => setStatus(e.target.value)}>{['DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'].map(s => <option key={s}>{s}</option>)}</select></label><label>Contenido (Markdown)<textarea style={{ minHeight: 300 }} value={body} onChange={e => setBody(e.target.value)} required /></label>{content.kind === 'CASE' && <label>Solución editorial<textarea value={data.modelAnswer ?? ''} onChange={e => setData({ ...data, modelAnswer: e.target.value })} /></label>}{data.questions.map((q, i) => <div className="stack" key={q.id}><label>Pregunta {i + 1}<input value={q.prompt} onChange={e => setData({ ...data, questions: data.questions.map((x, n) => n === i ? { ...x, prompt: e.target.value } : x) })} /></label><label>Explicación<textarea value={q.explanation} onChange={e => setData({ ...data, questions: data.questions.map((x, n) => n === i ? { ...x, explanation: e.target.value } : x) })} /></label><label>Opción correcta<select value={q.correct} onChange={e => setData({ ...data, questions: data.questions.map((x, n) => n === i ? { ...x, correct: Number(e.target.value) } : x) })}>{q.options.map((o, j) => <option key={j} value={j}>{o}</option>)}</select></label></div>)}<div className="actions"><button className="button" disabled={save.isPending}>Guardar nueva versión</button><button className="button secondary" type="button" onClick={onClose}>Volver</button></div></form>;
}
