'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { roles, modules } from 'shared';
import { api, post, patch } from '../../services/api';
import type { User, Page, Plan } from '../../types/api';
import { PageHeader, ErrorNotice, Loading } from '../../components/ui/common';
interface AdminUser extends User { status: string; subscription: { plan: Plan } | null; entitlements: { id: string; module: string; expiresAt: string | null; revokedAt: string | null }[]; }
export function AdminUsers({ id }: { id?: string }) {
  const [q, setQ] = useState(''); const [page, setPage] = useState(1); const [status, setStatus] = useState('');
  const query = useQuery({ queryKey: ['admin-users', q, page, status], queryFn: () => api<Page<AdminUser>>(`admin/users?q=${encodeURIComponent(q)}&page=${page}${status ? `&status=${status}` : ''}`), enabled: !id });
  if (id) return <AdminUserDetail id={id} />;
  return <><PageHeader title="Usuarios" description="Consulta cuentas, gestiona accesos y revisa su estado." /><div className="filters"><input aria-label="Buscar usuarios" placeholder="Nombre, usuario o email…" value={q} onChange={e => { setQ(e.target.value); setPage(1); }} /><select value={status} aria-label="Estado de usuario" onChange={e => setStatus(e.target.value)}><option value="">Todos los estados</option><option>ACTIVE</option><option>SUSPENDED</option><option>DISABLED</option></select></div><ErrorNotice error={query.error} />{query.isPending && <Loading />}<div className="panel table-scroll"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Plan</th><th>Acción</th></tr></thead><tbody>{query.data?.items.map(u => <tr key={u.id}><td><strong>{u.name}</strong><br />{u.email}</td><td>{u.role}</td><td>{u.status}</td><td>{u.subscription?.plan.name ?? 'Sin plan'}</td><td><Link href={`/admin/usuarios/${u.id}`}>Gestionar</Link></td></tr>)}</tbody></table></div><div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{query.data?.total ?? 0} usuarios · Página {page}</span><button className="button secondary" disabled={!query.data || page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div></>;
}
function AdminUserDetail({ id }: { id: string }) {
  const client = useQueryClient(); const [module, setModule] = useState<string>(modules[0]); const [expiresAt, setExpiresAt] = useState('');
  const query = useQuery({ queryKey: ['admin-user', id], queryFn: () => api<AdminUser>(`admin/users/${id}`) }); const me = useQuery({ queryKey: ['me'], queryFn: () => api<User>('auth/me') });
  const update = useMutation({ mutationFn: (data: unknown) => patch(`admin/users/${id}`, data), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-user', id] }) });
  const action = useMutation({ mutationFn: ({ path, data }: { path: string; data?: unknown }) => post(`admin/users/${id}/${path}`, data), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-user', id] }) });
  if (query.isPending) return <Loading />; if (!query.data) return <ErrorNotice error={query.error} />; const u = query.data;
  return <><Link href="/admin/usuarios">← Usuarios</Link><PageHeader title={u.name} description={`${u.email} · @${u.username} · ${u.status}`} /><ErrorNotice error={update.error ?? action.error} /><div className="two-columns"><section className="panel stack"><h2>Cuenta y sesiones</h2><div className="actions"><button className="button secondary" onClick={() => update.mutate({ status: 'ACTIVE' })}>Activar</button><button className="button secondary" onClick={() => update.mutate({ status: 'SUSPENDED' })}>Suspender</button><button className="button danger" onClick={() => update.mutate({ status: 'DISABLED' })}>Desactivar</button></div><p className="fine muted">Suspender o desactivar conserva el historial y revoca las sesiones inmediatamente.</p><button className="button secondary" onClick={() => action.mutate({ path: 'revoke-sessions' })}>Revocar todas las sesiones</button><label>Rol<select value={u.role} onChange={e => update.mutate({ role: e.target.value })} disabled={update.isPending}>{roles.filter(r => me.data?.role === 'SUPERADMIN' || !['ADMIN', 'SUPERADMIN'].includes(r)).map(r => <option key={r}>{r}</option>)}</select></label></section><section className="panel stack"><h2>Accesos manuales</h2><p>Plan: {u.subscription?.plan.name ?? 'Sin plan'}</p><label>Módulo<select value={module} onChange={e => setModule(e.target.value)}>{modules.map(m => <option key={m}>{m}</option>)}</select></label><label>Caducidad (opcional)<input type="datetime-local" value={expiresAt} onChange={e => setExpiresAt(e.target.value)} /></label><button className="button" disabled={action.isPending} onClick={() => action.mutate({ path: 'entitlements', data: { module, ...(expiresAt ? { expiresAt: new Date(expiresAt).toISOString() } : {}) } })}>Conceder acceso</button>{u.entitlements.filter(g => !g.revokedAt).map(g => <div key={g.id}><p>{g.module} · {g.expiresAt ? new Date(g.expiresAt).toLocaleString('es-ES') : 'Sin caducidad'}</p><button className="button secondary small" onClick={() => action.mutate({ path: `entitlements/${g.id}/revoke` })}>Retirar acceso</button></div>)}</section></div></>;
}
