'use client';
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { api, post, patch } from '../../services/api';
import type { User } from '../../types/api';
import { PageHeader, Loading, ErrorNotice } from '../../components/ui/common';
export function Account() {
  const query = useQuery({ queryKey: ['me'], queryFn: () => api<User>('auth/me') }); if (query.isPending) return <Loading />; if (!query.data) return <ErrorNotice error={query.error} />; return <AccountForm user={query.data} />;
}
function AccountForm({ user }: { user: User }) {
  const [name, setName] = useState(user.name); const [profile, setProfile] = useState({ profileType: user.profile.profileType ?? 'OPOSITOR', province: user.profile.province ?? '', municipality: user.profile.municipality ?? '', targetCall: user.profile.targetCall ?? '', timezone: user.profile.timezone ?? 'Europe/Madrid' }); const [currentPassword, setCurrent] = useState(''); const [password, setPassword] = useState(''); const client = useQueryClient(); const router = useRouter();
  const save = useMutation({ mutationFn: () => patch('auth/profile', { name, ...profile }), onSuccess: () => client.invalidateQueries({ queryKey: ['me'] }) });
  const revoke = useMutation({ mutationFn: () => post('auth/logout-others') });
  const change = useMutation({ mutationFn: () => post('auth/change-password', { currentPassword, password }), onSuccess: () => { client.clear(); router.push('/login'); } });
  const logout = useMutation({ mutationFn: () => post('auth/logout'), onSuccess: () => { client.clear(); router.push('/login'); } });
  return <><PageHeader eyebrow="TUS DATOS Y PREFERENCIAS" title="Mi cuenta" description={`${user.email} · @${user.username}`} /><div className="two-columns"><form method="post" className="panel stack" onSubmit={e => { e.preventDefault(); save.mutate(); }}><ErrorNotice error={save.error} /><label>Nombre<input value={name} onChange={e => setName(e.target.value)} required minLength={2} maxLength={100} /></label><label>Perfil<select value={profile.profileType} onChange={e => setProfile({ ...profile, profileType: e.target.value as typeof profile.profileType })}><option value="OPOSITOR">Opositor</option><option value="POLICIA_ACTIVO">Policía en activo</option><option value="HIBRIDO">Ambos</option></select></label>{(['province', 'municipality', 'targetCall', 'timezone'] as const).map((key, i) => <label key={key}>{['Provincia', 'Municipio objetivo', 'Convocatoria objetivo', 'Zona horaria'][i]}<input value={profile[key]} onChange={e => setProfile({ ...profile, [key]: e.target.value })} maxLength={100} /></label>)}<button className="button" disabled={save.isPending}>Guardar perfil</button>{save.isSuccess && <p role="status" className="notice success">Perfil actualizado.</p>}</form><div className="stack"><form method="post" className="panel stack" onSubmit={e => { e.preventDefault(); change.mutate(); }}><h2>Seguridad</h2><ErrorNotice error={change.error ?? revoke.error ?? logout.error} /><label>Contraseña actual<input type="password" value={currentPassword} onChange={e => setCurrent(e.target.value)} required autoComplete="current-password" /></label><label>Nueva contraseña<input type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={12} autoComplete="new-password" /></label><button className="button secondary" disabled={change.isPending}>Cambiar contraseña</button><button type="button" className="button secondary" disabled={revoke.isPending} onClick={() => revoke.mutate()}>Cerrar el resto de sesiones</button>{revoke.isSuccess && <p role="status">Resto de sesiones cerradas.</p>}</form><section className="panel stack"><Link href="/app/suscripcion">Gestionar mi plan →</Link><button className="button secondary" disabled={logout.isPending} onClick={() => logout.mutate()}>Cerrar sesión</button></section></div></div></>;
}
