'use client';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { api, post } from '../../services/api';
import type { Page } from '../../types/api';
import { PageHeader, ErrorNotice, Loading, Empty, ActionLink } from '../../components/ui/common';
interface ErrorItem { id: string; concept: string; action: string; status: string; count: number; nextReview: string; }
export function ErrorBank() {
  const [page, setPage] = useState(1); const client = useQueryClient(); const query = useQuery({ queryKey: ['errors', page], queryFn: () => api<Page<ErrorItem>>(`error-bank?page=${page}`) });
  const review = useMutation({ mutationFn: ({ id, rating }: { id: string; rating: string }) => post(`error-bank/${id}/review`, { rating }), onSuccess: () => { client.invalidateQueries({ queryKey: ['errors'] }); client.invalidateQueries({ queryKey: ['progress'] }); } });
  return <><PageHeader eyebrow="DEL ERROR AL CRITERIO" title="Tu banco de errores" description="Repasa el concepto, vuelve a practicar y valora cómo ha ido el repaso." /><ErrorNotice error={query.error ?? review.error} />{query.isPending && <Loading />}{query.data?.total === 0 && <Empty title="Aún no hay errores registrados" description="Los conceptos fallados en tus ejercicios aparecerán aquí con una propuesta de refuerzo." />}<div className="list">{query.data?.items.map(item => <article className="panel" key={item.id}><span className="tag">{item.status === 'MASTERED' ? 'Consolidado (autoevaluación)' : 'Pendiente de refuerzo'}</span><h2 style={{ marginTop: 14 }}>{item.concept}</h2><p>{item.action}</p><p className="fine muted">{item.count} veces registrado · Próximo repaso: {new Date(item.nextReview).toLocaleDateString('es-ES')}</p><div className="actions"><ActionLink href="/app/temario/metodo-universal" secondary>Revisar la ficha</ActionLink><button className="button secondary" disabled={review.isPending} onClick={() => review.mutate({ id: item.id, rating: 'DOUBT' })}>Aún tengo dudas · 3 días</button><button className="button secondary" disabled={review.isPending} onClick={() => review.mutate({ id: item.id, rating: 'CORRECT' })}>Repaso correcto · 5 días</button><button className="button secondary" disabled={review.isPending} onClick={() => review.mutate({ id: item.id, rating: 'MASTERED' })}>Consolidado · 10 días</button></div></article>)}</div>{query.data && query.data.total > 20 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</button><span>{page}</span><button disabled={page * 20 >= query.data.total} onClick={() => setPage(page + 1)}>Siguiente</button></div>}</>;
}
